const API_BASE_PATH = process.env.REACT_APP_BACKEND_URL;
const PASSWORD_MIN_LENGTH = 6

const TASK_STATUS_NAV_MENU = {
  ALL: "All",
  PENDING: "Pending",
  COMPLETED: "Completed",
}

export { PASSWORD_MIN_LENGTH, API_BASE_PATH, TASK_STATUS_NAV_MENU }
